[package]
name = "expr"
version = "0.1.0"
edition = "2024"

[dependencies]
ecow = "0.2.6"
notify-debouncer-full = "0.6.0"
strum = "0.27.2"
strum_macros = "0.27.2"

vello = "0.5.1"
anyhow = "1.0.99"
pollster = "0.4.0"
winit = "0.30.10"
